# Generated by Django 5.2.11 on 2026-02-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_be_app', '0003_user_is_active_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
