# Generated by Django 5.2.11 on 2026-02-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_be_app', '0004_rename_email_user_username_remove_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
