# Generated by Django 5.2.11 on 2026-02-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_be_app', '0005_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
